# fly.toml app configuration file generated for barbershop-mo-ma-api on 2026-05-31T23:53:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barbershop-mo-ma-api'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  docker_build_context = '.'

[env]
  NODE_ENV = 'production'
  PORT = '3001'
  REMINDER_CRON_SCHEDULE = '*/30 * * * *'

[[mounts]]
  source = 'data'
  destination = '/app/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
